---
title: "Code_Book"
output: html_document
---


Data Dictionary- TidyDataSet.txt

this data set is constructed by combining the test and training data from the
Human Activity Recognition Using Smartphones Data Set, and then extracting only
variables that conatian 'mean' or 'std' in their names.
the original data set can be found here:

http://archive.ics.uci.edu/ml/datasets/Human+Activity+Recognition+Using+Smartphones#




Subject_ID
    integer.  Id number of subject (person).

Activity
    Characer.  Description of activity the suject was engaed in when the
    measuemnets were taken.
    
The following variables are the average (mean) for each subject and activity
corresponidg to the variables in the Human Activity Recognition Using Smartphones Data Set.
'Avg_' is prepended to the variable names to indicate that they have been averaged.

The code book for the original data set, feature_info.txt, is inluded in the above link.

Avg_tBodyAcc_mean_X 

Avg_tBodyAcc_mean_Y

Avg_tBodyAcc_mean_Z

Avg_tBodyAcc_std_X

Avg_tBodyAcc_std_Y

Avg_tBodyAcc_std_Z               

Avg_tGravityAcc_mean_X

Avg_tGravityAcc_mean_Y

Avg_tGravityAcc_mean_Z

Avg_tGravityAcc_std_X

Avg_tGravityAcc_std_Y

Avg_tGravityAcc_std_Z

Avg_tBodyAccJerk_mean_X

Avg_tBodyAccJerk_mean_Y

Avg_tBodyAccJerk_mean_Z

Avg_tBodyAccJerk_std_X

Avg_tBodyAccJerk_std_Y

Avg_tBodyAccJerk_std_Z

Avg_tBodyGyro_mean_X  

Avg_tBodyGyro_mean_Y

Avg_tBodyGyro_mean_Z

Avg_tBodyGyro_std_X              

Avg_tBodyGyro_std_Y

Avg_tBodyGyro_std_Z

Avg_tBodyGyroJerk_mean_X

Avg_tBodyGyroJerk_mean_Y

Avg_tBodyGyroJerk_mean_Z

Avg_tBodyGyroJerk_std_X

Avg_tBodyGyroJerk_std_Y

Avg_tBodyGyroJerk_std_Z

Avg_tBodyAccMag_mean

Avg_tBodyAccMag_std

Avg_tGravityAccMag_mean

Avg_tGravityAccMag_std

Avg_tBodyAccJerkMag_mean

Avg_tBodyAccJerkMag_std

Avg_tBodyGyroMag_mean

Avg_tBodyGyroMag_std             

Avg_tBodyGyroJerkMag_mean

Avg_tBodyGyroJerkMag_std

Avg_fBodyAcc_mean_X

Avg_fBodyAcc_mean_Y              

Avg_fBodyAcc_mean_Z

Avg_fBodyAcc_std_X

Avg_fBodyAcc_std_Y

Avg_fBodyAcc_std_Z               

Avg_fBodyAcc_meanFreq_X

Avg_fBodyAcc_meanFreq_Y

Avg_fBodyAcc_meanFreq_Z

Avg_fBodyAccJerk_mean_X

Avg_fBodyAccJerk_mean_Y

Avg_fBodyAccJerk_mean_Z

Avg_fBodyAccJerk_std_X

Avg_fBodyAccJerk_std_Y

Avg_fBodyAccJerk_std_Z

Avg_fBodyAccJerk_meanFreq_X

Avg_fBodyAccJerk_meanFreq_Y

Avg_fBodyAccJerk_meanFreq_Z

Avg_fBodyGyro_mean_X

Avg_fBodyGyro_mean_Y

Avg_fBodyGyro_mean_Z

Avg_fBodyGyro_std_X              

Avg_fBodyGyro_std_Y

Avg_fBodyGyro_std_Z

Avg_fBodyGyro_meanFreq_X

Avg_fBodyGyro_meanFreq_Y

Avg_fBodyGyro_meanFreq_Z

Avg_fBodyAccMag_mean

Avg_fBodyAccMag_std

Avg_fBodyAccMag_meanFreq

Avg_fBodyBodyAccJerkMag_mean

Avg_fBodyBodyAccJerkMag_std

Avg_fBodyBodyAccJerkMag_meanFreq

Avg_fBodyBodyGyroMag_mean

Avg_fBodyBodyGyroMag_std

Avg_fBodyBodyGyroMag_meanFreq

Avg_fBodyBodyGyroJerkMag_mean

Avg_fBodyBodyGyroJerkMag_std

Avg_fBodyBodyGyroJerkMag_meanFreq